### ISSUE TITLE
Fnbounds spawn is slow with large memory spaces

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpctoolkit#458]
This is a bug originally found by @Lucindaaaa, reduced by her in #420, fixed by me in #423, and then re-broken by me in #456. Present in `master`.

When the application memory space is very large (e.g. multi-GB applications) there is a noticeable performance cost from the fork-like `clone()` used to spawn Fnbounds. Current understanding is that this cost comes from cloning the page table for copy-on-write semantics in the child process with 4K pages.

As noted elsewhere, we are prevented from spawning a process without cloning the page table on RHEL 7.x (running Glibc 2.17) because of a bug in Glibc <2.24 where a `clone()` using `CLONE_VM` (and not `CLONE_THREAD`) messes up bits in the parent (https://sourceware.org/bugzilla/show_bug.cgi?id=19957).

[bigmemtest.txt](https://github.com/HPCToolkit/hpctoolkit/files/7381588/bigmemtest.txt) (sorry for the funny name, GitHub is annoying) is a simple reproducer for this bug which allocates (and `mlock`s) a large memory region and then `dlopen`s a binary to time the spawning of Fnbounds. Failure is indicated by a significant increase in the time taken for `dlopen`s after the memory allocation. On my x86-64 system using 27 of my 32 GB of memory:
```console
$ gcc -o bigmemtest bigmemtest.c -ldl
$ hpcrun --fnbounds-eager-shutdown ./bigmemtest $((27*1024*1024*1024)) libm.so.6
Hello world!
Timing a quick dlopen to respawn fnbounds (use --fnbounds-eager-shutdown)...
Time taken: 0.000922
Time taken: 0.002065
Time taken: 0.002111
Mapping and locking 28991029248 bytes of memory...
Timing a quick dlopen to respawn fnbounds (use --fnbounds-eager-shutdown)...
Time taken: 0.117133
Time taken: 0.109942
Time taken: 0.108893
```

**Comment by jmellorcrummey** [comment]
fixed with #209

**Comment by blue42u** [comment]
AFAICT this is still an issue, the code has not changed since #456. If we ever drop support for Glibc <2.24 that PR can be reverted and this issue can be fixed.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/458)
